# Generated by Django 3.2.5 on 2023-06-14 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_contact_email_alter_contact_message_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featuredproduct',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
    ]
