# Generated by Django 3.2.5 on 2022-10-08 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='welcomeinformation',
            options={'verbose_name_plural': 'Welcome  Information'},
        ),
    ]
