# Generated by Django 3.2.5 on 2022-10-08 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_welcomeinformation_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='welcomeinformation',
            name='description',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
