# Generated by Django 3.2.5 on 2022-10-08 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_welcomeinformation_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='welcomeinformation',
            name='ownerImage',
            field=models.ImageField(blank=True, null=True, upload_to='welcome'),
        ),
        migrations.AddField(
            model_name='welcomeinformation',
            name='secondOwnerImage',
            field=models.ImageField(blank=True, null=True, upload_to='welcome'),
        ),
        migrations.AddField(
            model_name='welcomeinformation',
            name='thirdOwnerImage',
            field=models.ImageField(blank=True, null=True, upload_to='welcome'),
        ),
        migrations.AddField(
            model_name='welcomeinformation',
            name='titleImage',
            field=models.ImageField(blank=True, null=True, upload_to='welcome'),
        ),
    ]
