# Generated by Django 3.2.5 on 2022-10-09 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_wheretostart_indexer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wheretostart',
            name='Indexer',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='wheretostart',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
