# Generated by Django 3.2.5 on 2022-10-10 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_alter_blogarticles_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogarticles',
            name='articleCategory',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
