# Generated by Django 3.2.5 on 2022-10-10 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_blogarticles_articlecategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogarticles',
            name='articleDescription',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
