# Generated by Django 3.2.5 on 2022-10-10 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_blogarticles_articledescription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogarticles',
            name='articleDescription',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
