# Generated by Django 3.2.5 on 2022-10-18 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_whatsnew'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='whatsnew',
            options={'verbose_name_plural': "What's  New"},
        ),
        migrations.AddField(
            model_name='blogarticles',
            name='date_modified',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
