# Generated by Django 3.2.5 on 2022-10-18 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_auto_20221018_0826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogarticles',
            name='date_modified',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
