# Generated by Django 3.2.5 on 2022-10-18 06:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_alter_blogarticles_date_modified'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Scripture', 'Scripture'), ('Life', 'Life'), ('Health', 'Health'), ('Fashion', 'Fashion'), ('Beauty', 'Beauty')], max_length=200, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='categories')),
            ],
        ),
        migrations.AlterField(
            model_name='blogarticles',
            name='articleCategory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.categories'),
        ),
    ]
