# Generated by Django 3.2.5 on 2022-10-18 06:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogarticles',
            name='articleCategory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.categories'),
        ),
    ]
