# Generated by Django 3.2.5 on 2022-10-18 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_auto_20221018_1012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='pargraph_1',
            field=models.TextField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='about',
            name='pargraph_2',
            field=models.TextField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='about',
            name='pargraph_3',
            field=models.TextField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='about',
            name='pargraph_4',
            field=models.TextField(blank=True, max_length=10000, null=True),
        ),
    ]
