# Generated by Django 3.2.5 on 2022-10-18 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0023_auto_20221018_1016'),
    ]

    operations = [
        migrations.RenameField(
            model_name='about',
            old_name='pargraph_1',
            new_name='paragraph_1',
        ),
        migrations.RenameField(
            model_name='about',
            old_name='pargraph_2',
            new_name='paragraph_2',
        ),
        migrations.RenameField(
            model_name='about',
            old_name='pargraph_3',
            new_name='paragraph_3',
        ),
        migrations.RenameField(
            model_name='about',
            old_name='pargraph_4',
            new_name='paragraph_4',
        ),
    ]
