# Generated by Django 3.2.5 on 2023-01-02 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0026_auto_20221018_1117'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WhatsNew',
        ),
        migrations.AddField(
            model_name='wheretostart',
            name='slug',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='blogarticles',
            name='date_added',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
