# Generated by Django 3.2.5 on 2023-01-02 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0027_auto_20230102_2319'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='mainimage',
            field=models.ImageField(blank=True, null=True, upload_to='blog'),
        ),
    ]
